### ISSUE TITLE
Es sollten wenigstens zwei Personen mitessen!

### ISSUE THREAD

**Issue by p410n3** [archi/wzet#20]
![pic](https://i.imgur.com/kFjz8iq.png)

Entweder verstehe ich nicht ganz wie das funktioneren soll, aber wenn ich mich + 2 personen als Teilnehmer angebe _sollte_ es doch klappen? Sobald ich alle 3 user auswähle geht es. Hoffe ich habe es nicht einfach falsch verstanden...

![pic](https://i.imgur.com/ArAJZ75.png)

**Comment by archi** [comment]
Ersteres sieht schon was komisch aus: Der Check sollte eigentlich zwei Nutzer zählen (und 2+21 Mitesser). Dass der Bezahler nicht mit isst, soll erlaubt sein.
Da ist also irgendwas nicht ok.

Das zweite ist der Check, dass man die Zahl in der Rechnung geändert hat.
Könnte man eigentlich durch einen grauen Beispielwert ersetzen (der ist da, damit die Leute sehen, dass ',' okay ist - wobei das Tool sowohl ',' als auch '.' als Dezimaltrennzeichen akzeptiert) - aber im Prinzip ist das so Absicht.

**Comment by p410n3** [comment]
5e73c81cebedf569c24b16f5afb1c69c09a1a051

War schonmal ein kleiner Fehler.

**Comment by archi** [comment]
Jepp. Kleinvieh macht auch Mist. Wir haben hier schon über richtiges CI gesprochen, damit wäre das natürlich aufgefallen -- aber ist für die Anzahl der Installationen leider ziemlicher Overkill.
